#!/usr/bin/env python3
"""Evaluate nflfastR win-probability predictions in local PBP parquet files.

The nflverse play-by-play releases already contain the `wp` and `vegas_wp`
columns generated by nflfastR. This script scores those predictions against the
eventual winner of each game, then writes summary and calibration CSV files.
It intentionally reads only the columns needed for evaluation, so all seasons
can be evaluated without loading the full PBP schema into memory.
"""

from __future__ import annotations

import argparse
import csv
import math
from collections import defaultdict
from pathlib import Path
from typing import Iterable

try:
    import pyarrow.dataset as ds
except ImportError as exc:  # pragma: no cover - exercised only without the dependency
    raise SystemExit(
        "pyarrow is required. Install the project dependency with: "
        "python3 -m pip install -r requirements.txt"
    ) from exc


def parse_args() -> argparse.Namespace:
    parser = argparse.ArgumentParser(
        description="Score nflfastR wp and/or vegas_wp against game outcomes."
    )
    parser.add_argument(
        "--data-dir",
        type=Path,
        default=Path("data/raw/pbp"),
        help="Directory containing play_by_play_<season>.parquet files.",
    )
    parser.add_argument(
        "--seasons",
        nargs="+",
        type=int,
        help="Specific seasons to evaluate; defaults to every local season file.",
    )
    parser.add_argument(
        "--predictions",
        nargs="+",
        choices=("wp", "vegas_wp"),
        default=("wp", "vegas_wp"),
        help="Prediction columns to score.",
    )
    parser.add_argument(
        "--output-dir",
        type=Path,
        default=Path("results"),
        help="Directory for wp_evaluation.csv and wp_calibration.csv.",
    )
    return parser.parse_args()


def season_files(data_dir: Path, seasons: Iterable[int] | None) -> list[Path]:
    if seasons:
        paths = [data_dir / f"play_by_play_{season}.parquet" for season in seasons]
        missing = [path for path in paths if not path.is_file()]
        if missing:
            missing_text = ", ".join(str(path) for path in missing)
            raise SystemExit(f"Missing requested parquet file(s): {missing_text}")
        return paths

    paths = sorted(data_dir.glob("play_by_play_*.parquet"))
    if not paths:
        raise SystemExit(
            f"No play-by-play parquet files found in {data_dir}. "
            "Run scripts/download_nflfastR_assets.sh first."
        )
    return paths


def as_float(value: object) -> float | None:
    if value is None:
        return None
    try:
        result = float(value)
    except (TypeError, ValueError):
        return None
    return result if math.isfinite(result) else None


def evaluate_prediction(
    name: str,
    values: Iterable[tuple[object, object, object, object, object, object, object]],
) -> tuple[dict[str, object], list[dict[str, object]]]:
    brier_sum = 0.0
    log_loss_sum = 0.0
    prediction_sum = 0.0
    label_sum = 0.0
    n_plays = 0
    games: set[str] = set()
    bins: dict[int, dict[str, float]] = defaultdict(
        lambda: {"n_plays": 0, "prediction_sum": 0.0, "label_sum": 0.0}
    )

    for season, game_id, result, home_team, away_team, posteam, prediction in values:
        probability = as_float(prediction)
        margin = as_float(result)
        if probability is None or margin is None or game_id is None:
            continue
        if not (0.0 <= probability <= 1.0):
            continue
        if margin == 0.0:  # Ties do not have a binary winner label.
            continue
        if posteam is None or home_team is None or away_team is None:
            continue

        if posteam == home_team:
            label = 1.0 if margin > 0.0 else 0.0
        elif posteam == away_team:
            label = 0.0 if margin > 0.0 else 1.0
        else:
            continue

        clipped = min(max(probability, 1e-15), 1.0 - 1e-15)
        brier_sum += (probability - label) ** 2
        log_loss_sum -= label * math.log(clipped) + (1.0 - label) * math.log(1.0 - clipped)
        prediction_sum += probability
        label_sum += label
        n_plays += 1
        games.add(f"{season}:{game_id}")

        bin_number = min(int(probability * 10.0), 9)
        bins[bin_number]["n_plays"] += 1
        bins[bin_number]["prediction_sum"] += probability
        bins[bin_number]["label_sum"] += label

    if n_plays == 0:
        raise SystemExit(f"No valid rows found for prediction column {name!r}.")

    # For a binary label, the 0.5 baseline Brier score is exactly 0.25.
    summary = {
        "prediction": name,
        "n_plays": n_plays,
        "n_games": len(games),
        "mean_prediction": prediction_sum / n_plays,
        "actual_win_rate": label_sum / n_plays,
        "brier_score": brier_sum / n_plays,
        "brier_baseline_0_5": 0.25,
        "brier_skill_vs_0_5": 1.0 - (brier_sum / n_plays) / 0.25,
        "log_loss": log_loss_sum / n_plays,
    }

    calibration = []
    for bin_number in range(10):
        bucket = bins[bin_number]
        count = int(bucket["n_plays"])
        if count == 0:
            continue
        calibration.append(
            {
                "prediction": name,
                "bin_lower": bin_number / 10.0,
                "bin_upper": (bin_number + 1) / 10.0,
                "n_plays": count,
                "mean_prediction": bucket["prediction_sum"] / count,
                "actual_win_rate": bucket["label_sum"] / count,
            }
        )
    return summary, calibration


def write_csv(path: Path, rows: list[dict[str, object]]) -> None:
    if not rows:
        return
    path.parent.mkdir(parents=True, exist_ok=True)
    with path.open("w", newline="") as handle:
        writer = csv.DictWriter(handle, fieldnames=list(rows[0]))
        writer.writeheader()
        writer.writerows(rows)


def main() -> None:
    args = parse_args()
    paths = season_files(args.data_dir, args.seasons)
    dataset = ds.dataset(paths, format="parquet")
    available = set(dataset.schema.names)
    required = {"season", "game_id", "result", "home_team", "away_team", "posteam"}
    missing = sorted(required - available)
    if missing:
        raise SystemExit(f"PBP data is missing required column(s): {', '.join(missing)}")
    missing_predictions = sorted(set(args.predictions) - available)
    if missing_predictions:
        raise SystemExit(
            "PBP data is missing prediction column(s): "
            + ", ".join(missing_predictions)
        )

    columns = [
        "season",
        "game_id",
        "result",
        "home_team",
        "away_team",
        "posteam",
        *args.predictions,
    ]
    table = dataset.to_table(columns=columns)
    columns_as_lists = {name: table[name].to_pylist() for name in columns}
    rows = zip(*(columns_as_lists[name] for name in columns))
    # Reuse the row values for each prediction column without reading the files again.
    row_list = list(rows)

    summaries = []
    calibrations = []
    for prediction in args.predictions:
        prediction_index = columns.index(prediction)
        scored_rows = (
            (
                row[0],
                row[1],
                row[2],
                row[3],
                row[4],
                row[5],
                row[prediction_index],
            )
            for row in row_list
        )
        summary, calibration = evaluate_prediction(prediction, scored_rows)
        summaries.append(summary)
        calibrations.extend(calibration)

    write_csv(args.output_dir / "wp_evaluation.csv", summaries)
    write_csv(args.output_dir / "wp_calibration.csv", calibrations)

    print(f"Evaluated {len(paths)} season file(s):")
    for path in paths:
        print(f"  {path}")
    for summary in summaries:
        print(
            f"{summary['prediction']}: "
            f"plays={summary['n_plays']:,}, games={summary['n_games']:,}, "
            f"brier={summary['brier_score']:.4f}, "
            f"log_loss={summary['log_loss']:.4f}"
        )
    print(f"Wrote {args.output_dir / 'wp_evaluation.csv'}")
    print(f"Wrote {args.output_dir / 'wp_calibration.csv'}")


if __name__ == "__main__":
    main()
